/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IterationsRouteImport } from './routes/iterations'
import { Route as MusicRouteImport } from './routes/music'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as PhotographyRouteImport } from './routes/photography'
import { Route as ImagesSplatRouteImport } from './routes/images.$'
import { Route as ApiAuthGithubRouteImport } from './routes/api.auth.github'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiMusicBaselineRouteImport } from './routes/api.music.baseline'
import { Route as ApiMusicDestinationsRouteImport } from './routes/api.music.destinations'
import { Route as ApiMusicReviewPlaylistRouteImport } from './routes/api.music.review-playlist'
import { Route as ApiMusicRunsRouteImport } from './routes/api.music.runs'
import { Route as ApiSpotifyCallbackRouteImport } from './routes/api.spotify.callback'
import { Route as ApiSpotifyConnectRouteImport } from './routes/api.spotify.connect'
import { Route as ApiSpotifyDisconnectRouteImport } from './routes/api.spotify.disconnect'
import { Route as ApiSpotifyLikedTracksRouteImport } from './routes/api.spotify.liked-tracks'
import { Route as ApiSpotifyPlaylistsRouteImport } from './routes/api.spotify.playlists'
import { Route as ApiSpotifyStatusRouteImport } from './routes/api.spotify.status'
import { Route as ApiAuthGithubCallbackRouteImport } from './routes/api.auth.github.callback'
import { Route as ApiMusicBaselineRetryRouteImport } from './routes/api.music.baseline.retry'
import { Route as ApiMusicDestinationsCreateRouteImport } from './routes/api.music.destinations.create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IterationsRoute = IterationsRouteImport.update({
  id: '/iterations',
  path: '/iterations',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyRoute = PhotographyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesSplatRoute = ImagesSplatRouteImport.update({
  id: '/images/$',
  path: '/images/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGithubRoute = ApiAuthGithubRouteImport.update({
  id: '/api/auth/github',
  path: '/api/auth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMusicBaselineRoute = ApiMusicBaselineRouteImport.update({
  id: '/api/music/baseline',
  path: '/api/music/baseline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMusicDestinationsRoute = ApiMusicDestinationsRouteImport.update({
  id: '/api/music/destinations',
  path: '/api/music/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMusicReviewPlaylistRoute = ApiMusicReviewPlaylistRouteImport.update({
  id: '/api/music/review-playlist',
  path: '/api/music/review-playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMusicRunsRoute = ApiMusicRunsRouteImport.update({
  id: '/api/music/runs',
  path: '/api/music/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyCallbackRoute = ApiSpotifyCallbackRouteImport.update({
  id: '/api/spotify/callback',
  path: '/api/spotify/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyConnectRoute = ApiSpotifyConnectRouteImport.update({
  id: '/api/spotify/connect',
  path: '/api/spotify/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyDisconnectRoute = ApiSpotifyDisconnectRouteImport.update({
  id: '/api/spotify/disconnect',
  path: '/api/spotify/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyLikedTracksRoute = ApiSpotifyLikedTracksRouteImport.update({
  id: '/api/spotify/liked-tracks',
  path: '/api/spotify/liked-tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyPlaylistsRoute = ApiSpotifyPlaylistsRouteImport.update({
  id: '/api/spotify/playlists',
  path: '/api/spotify/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyStatusRoute = ApiSpotifyStatusRouteImport.update({
  id: '/api/spotify/status',
  path: '/api/spotify/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGithubCallbackRoute = ApiAuthGithubCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGithubRoute,
} as any)
const ApiMusicBaselineRetryRoute = ApiMusicBaselineRetryRouteImport.update({
  id: '/retry',
  path: '/retry',
  getParentRoute: () => ApiMusicBaselineRoute,
} as any)
const ApiMusicDestinationsCreateRoute =
  ApiMusicDestinationsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => ApiMusicDestinationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/iterations': typeof IterationsRoute
  '/music': typeof MusicRoute
  '/personal': typeof PersonalRoute
  '/photography': typeof PhotographyRoute
  '/images/$': typeof ImagesSplatRoute
  '/api/auth/github': typeof ApiAuthGithubRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/music/baseline': typeof ApiMusicBaselineRouteWithChildren
  '/api/music/destinations': typeof ApiMusicDestinationsRouteWithChildren
  '/api/music/review-playlist': typeof ApiMusicReviewPlaylistRoute
  '/api/music/runs': typeof ApiMusicRunsRoute
  '/api/spotify/callback': typeof ApiSpotifyCallbackRoute
  '/api/spotify/connect': typeof ApiSpotifyConnectRoute
  '/api/spotify/disconnect': typeof ApiSpotifyDisconnectRoute
  '/api/spotify/liked-tracks': typeof ApiSpotifyLikedTracksRoute
  '/api/spotify/playlists': typeof ApiSpotifyPlaylistsRoute
  '/api/spotify/status': typeof ApiSpotifyStatusRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/music/baseline/retry': typeof ApiMusicBaselineRetryRoute
  '/api/music/destinations/create': typeof ApiMusicDestinationsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/iterations': typeof IterationsRoute
  '/music': typeof MusicRoute
  '/personal': typeof PersonalRoute
  '/photography': typeof PhotographyRoute
  '/images/$': typeof ImagesSplatRoute
  '/api/auth/github': typeof ApiAuthGithubRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/music/baseline': typeof ApiMusicBaselineRouteWithChildren
  '/api/music/destinations': typeof ApiMusicDestinationsRouteWithChildren
  '/api/music/review-playlist': typeof ApiMusicReviewPlaylistRoute
  '/api/music/runs': typeof ApiMusicRunsRoute
  '/api/spotify/callback': typeof ApiSpotifyCallbackRoute
  '/api/spotify/connect': typeof ApiSpotifyConnectRoute
  '/api/spotify/disconnect': typeof ApiSpotifyDisconnectRoute
  '/api/spotify/liked-tracks': typeof ApiSpotifyLikedTracksRoute
  '/api/spotify/playlists': typeof ApiSpotifyPlaylistsRoute
  '/api/spotify/status': typeof ApiSpotifyStatusRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/music/baseline/retry': typeof ApiMusicBaselineRetryRoute
  '/api/music/destinations/create': typeof ApiMusicDestinationsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/iterations': typeof IterationsRoute
  '/music': typeof MusicRoute
  '/personal': typeof PersonalRoute
  '/photography': typeof PhotographyRoute
  '/images/$': typeof ImagesSplatRoute
  '/api/auth/github': typeof ApiAuthGithubRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/music/baseline': typeof ApiMusicBaselineRouteWithChildren
  '/api/music/destinations': typeof ApiMusicDestinationsRouteWithChildren
  '/api/music/review-playlist': typeof ApiMusicReviewPlaylistRoute
  '/api/music/runs': typeof ApiMusicRunsRoute
  '/api/spotify/callback': typeof ApiSpotifyCallbackRoute
  '/api/spotify/connect': typeof ApiSpotifyConnectRoute
  '/api/spotify/disconnect': typeof ApiSpotifyDisconnectRoute
  '/api/spotify/liked-tracks': typeof ApiSpotifyLikedTracksRoute
  '/api/spotify/playlists': typeof ApiSpotifyPlaylistsRoute
  '/api/spotify/status': typeof ApiSpotifyStatusRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/music/baseline/retry': typeof ApiMusicBaselineRetryRoute
  '/api/music/destinations/create': typeof ApiMusicDestinationsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/iterations'
    | '/music'
    | '/personal'
    | '/photography'
    | '/images/$'
    | '/api/auth/github'
    | '/api/auth/logout'
    | '/api/music/baseline'
    | '/api/music/destinations'
    | '/api/music/review-playlist'
    | '/api/music/runs'
    | '/api/spotify/callback'
    | '/api/spotify/connect'
    | '/api/spotify/disconnect'
    | '/api/spotify/liked-tracks'
    | '/api/spotify/playlists'
    | '/api/spotify/status'
    | '/api/auth/github/callback'
    | '/api/music/baseline/retry'
    | '/api/music/destinations/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/iterations'
    | '/music'
    | '/personal'
    | '/photography'
    | '/images/$'
    | '/api/auth/github'
    | '/api/auth/logout'
    | '/api/music/baseline'
    | '/api/music/destinations'
    | '/api/music/review-playlist'
    | '/api/music/runs'
    | '/api/spotify/callback'
    | '/api/spotify/connect'
    | '/api/spotify/disconnect'
    | '/api/spotify/liked-tracks'
    | '/api/spotify/playlists'
    | '/api/spotify/status'
    | '/api/auth/github/callback'
    | '/api/music/baseline/retry'
    | '/api/music/destinations/create'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/iterations'
    | '/music'
    | '/personal'
    | '/photography'
    | '/images/$'
    | '/api/auth/github'
    | '/api/auth/logout'
    | '/api/music/baseline'
    | '/api/music/destinations'
    | '/api/music/review-playlist'
    | '/api/music/runs'
    | '/api/spotify/callback'
    | '/api/spotify/connect'
    | '/api/spotify/disconnect'
    | '/api/spotify/liked-tracks'
    | '/api/spotify/playlists'
    | '/api/spotify/status'
    | '/api/auth/github/callback'
    | '/api/music/baseline/retry'
    | '/api/music/destinations/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  IterationsRoute: typeof IterationsRoute
  MusicRoute: typeof MusicRoute
  PersonalRoute: typeof PersonalRoute
  PhotographyRoute: typeof PhotographyRoute
  ImagesSplatRoute: typeof ImagesSplatRoute
  ApiAuthGithubRoute: typeof ApiAuthGithubRouteWithChildren
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiMusicBaselineRoute: typeof ApiMusicBaselineRouteWithChildren
  ApiMusicDestinationsRoute: typeof ApiMusicDestinationsRouteWithChildren
  ApiMusicReviewPlaylistRoute: typeof ApiMusicReviewPlaylistRoute
  ApiMusicRunsRoute: typeof ApiMusicRunsRoute
  ApiSpotifyCallbackRoute: typeof ApiSpotifyCallbackRoute
  ApiSpotifyConnectRoute: typeof ApiSpotifyConnectRoute
  ApiSpotifyDisconnectRoute: typeof ApiSpotifyDisconnectRoute
  ApiSpotifyLikedTracksRoute: typeof ApiSpotifyLikedTracksRoute
  ApiSpotifyPlaylistsRoute: typeof ApiSpotifyPlaylistsRoute
  ApiSpotifyStatusRoute: typeof ApiSpotifyStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iterations': {
      id: '/iterations'
      path: '/iterations'
      fullPath: '/iterations'
      preLoaderRoute: typeof IterationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/$': {
      id: '/images/$'
      path: '/images/$'
      fullPath: '/images/$'
      preLoaderRoute: typeof ImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github': {
      id: '/api/auth/github'
      path: '/api/auth/github'
      fullPath: '/api/auth/github'
      preLoaderRoute: typeof ApiAuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/music/baseline': {
      id: '/api/music/baseline'
      path: '/api/music/baseline'
      fullPath: '/api/music/baseline'
      preLoaderRoute: typeof ApiMusicBaselineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/music/destinations': {
      id: '/api/music/destinations'
      path: '/api/music/destinations'
      fullPath: '/api/music/destinations'
      preLoaderRoute: typeof ApiMusicDestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/music/review-playlist': {
      id: '/api/music/review-playlist'
      path: '/api/music/review-playlist'
      fullPath: '/api/music/review-playlist'
      preLoaderRoute: typeof ApiMusicReviewPlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/music/runs': {
      id: '/api/music/runs'
      path: '/api/music/runs'
      fullPath: '/api/music/runs'
      preLoaderRoute: typeof ApiMusicRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/callback': {
      id: '/api/spotify/callback'
      path: '/api/spotify/callback'
      fullPath: '/api/spotify/callback'
      preLoaderRoute: typeof ApiSpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/connect': {
      id: '/api/spotify/connect'
      path: '/api/spotify/connect'
      fullPath: '/api/spotify/connect'
      preLoaderRoute: typeof ApiSpotifyConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/disconnect': {
      id: '/api/spotify/disconnect'
      path: '/api/spotify/disconnect'
      fullPath: '/api/spotify/disconnect'
      preLoaderRoute: typeof ApiSpotifyDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/liked-tracks': {
      id: '/api/spotify/liked-tracks'
      path: '/api/spotify/liked-tracks'
      fullPath: '/api/spotify/liked-tracks'
      preLoaderRoute: typeof ApiSpotifyLikedTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/playlists': {
      id: '/api/spotify/playlists'
      path: '/api/spotify/playlists'
      fullPath: '/api/spotify/playlists'
      preLoaderRoute: typeof ApiSpotifyPlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify/status': {
      id: '/api/spotify/status'
      path: '/api/spotify/status'
      fullPath: '/api/spotify/status'
      preLoaderRoute: typeof ApiSpotifyStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github/callback': {
      id: '/api/auth/github/callback'
      path: '/callback'
      fullPath: '/api/auth/github/callback'
      preLoaderRoute: typeof ApiAuthGithubCallbackRouteImport
      parentRoute: typeof ApiAuthGithubRoute
    }
    '/api/music/baseline/retry': {
      id: '/api/music/baseline/retry'
      path: '/retry'
      fullPath: '/api/music/baseline/retry'
      preLoaderRoute: typeof ApiMusicBaselineRetryRouteImport
      parentRoute: typeof ApiMusicBaselineRoute
    }
    '/api/music/destinations/create': {
      id: '/api/music/destinations/create'
      path: '/create'
      fullPath: '/api/music/destinations/create'
      preLoaderRoute: typeof ApiMusicDestinationsCreateRouteImport
      parentRoute: typeof ApiMusicDestinationsRoute
    }
  }
}

interface ApiAuthGithubRouteChildren {
  ApiAuthGithubCallbackRoute: typeof ApiAuthGithubCallbackRoute
}

const ApiAuthGithubRouteChildren: ApiAuthGithubRouteChildren = {
  ApiAuthGithubCallbackRoute: ApiAuthGithubCallbackRoute,
}

const ApiAuthGithubRouteWithChildren = ApiAuthGithubRoute._addFileChildren(
  ApiAuthGithubRouteChildren,
)

interface ApiMusicBaselineRouteChildren {
  ApiMusicBaselineRetryRoute: typeof ApiMusicBaselineRetryRoute
}

const ApiMusicBaselineRouteChildren: ApiMusicBaselineRouteChildren = {
  ApiMusicBaselineRetryRoute: ApiMusicBaselineRetryRoute,
}

const ApiMusicBaselineRouteWithChildren =
  ApiMusicBaselineRoute._addFileChildren(ApiMusicBaselineRouteChildren)

interface ApiMusicDestinationsRouteChildren {
  ApiMusicDestinationsCreateRoute: typeof ApiMusicDestinationsCreateRoute
}

const ApiMusicDestinationsRouteChildren: ApiMusicDestinationsRouteChildren = {
  ApiMusicDestinationsCreateRoute: ApiMusicDestinationsCreateRoute,
}

const ApiMusicDestinationsRouteWithChildren =
  ApiMusicDestinationsRoute._addFileChildren(ApiMusicDestinationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  IterationsRoute: IterationsRoute,
  MusicRoute: MusicRoute,
  PersonalRoute: PersonalRoute,
  PhotographyRoute: PhotographyRoute,
  ImagesSplatRoute: ImagesSplatRoute,
  ApiAuthGithubRoute: ApiAuthGithubRouteWithChildren,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiMusicBaselineRoute: ApiMusicBaselineRouteWithChildren,
  ApiMusicDestinationsRoute: ApiMusicDestinationsRouteWithChildren,
  ApiMusicReviewPlaylistRoute: ApiMusicReviewPlaylistRoute,
  ApiMusicRunsRoute: ApiMusicRunsRoute,
  ApiSpotifyCallbackRoute: ApiSpotifyCallbackRoute,
  ApiSpotifyConnectRoute: ApiSpotifyConnectRoute,
  ApiSpotifyDisconnectRoute: ApiSpotifyDisconnectRoute,
  ApiSpotifyLikedTracksRoute: ApiSpotifyLikedTracksRoute,
  ApiSpotifyPlaylistsRoute: ApiSpotifyPlaylistsRoute,
  ApiSpotifyStatusRoute: ApiSpotifyStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
